# Generated by Django 4.2.2 on 2024-03-31 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_options_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('change_product_description', 'Can change product description'), ('change_product_category', 'Can change product category'), ('change_product_is_published', 'Can change product is_published')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
